theme:                      "serbianentrepreneurs-v2"
title:                      "Serbian Entrepreneurs"
config:                     "config.yaml"
defaultExtension:           "md"
MetaDataFormat:             "yaml"
LanguageCode:               "en"
baseURL: "https://www.SerbianEntrepreneurs.com/"
Params:
    URL: "https://SerbianEntrepreneurs.com/"
    SocialImage: "/images/cover.jpg"
    NextMeetingNYC:
        Month: "October"
        Day: "26"
    NextMeetingSF:
        Month: "October"
        Day: "26"
    description: "A pay-it-forward global network of entrepreneurs fostering the Serbian startup ecosystem."
    about: "Serbian Entrepreneurs is a non-profit organization started in September 2016 fostering the Serbian startup ecosystem around the globe through holistic access to skills, resources, and mentorship. We promote entrepreneurship through empowering the pay-it-forward activities of our members. Our 75 referral-based members are accomplished founders, investors, engineering leaders, and startup executives that together form a deeply vested network. Our monthly meetings provide a learning, operations, networking, and investment platform and take place in our founding city chapters: San Francisco and New York."
    email: "contact@serbianentrepreneurs.com"
    Members:
      - name: Dragan Petrovic
        description: COO, Nura
        image: "/images/pics/dragan.jpg"
      - name: Brano Perkovich
        description: Investor, SF 49ers
        image: "/images/pics/brano.jpg"
      - name: Tihomir Bajic
        description: VP Engineering, LTSE
        image: "/images/pics/tiho.jpg"
      - name: Sasha Novakovich
        description: CEO, Alchemy
        image: "/images/pics/sasha.jpg"
      - name: Maja Zecevic
        description: CEO, Opionato
        image: "/images/pics/maja.jpg"
      - name: Lazar Stojkovic
        description: Mentor, 500 Startups
        image: "/images/pics/lazar.jpg"
      - name: John Milinovich
        description: CEO, URX (Exited)
        image: "/images/pics/john.jpg"
      - name: Luka Erceg
        description: CEO, Drylet
        image: "/images/pics/luka.jpg"
      - name: Marko Mandic
        description: CEO, Breza
        image: "/images/pics/marko.jpg"
      - name: Olja Dimitrijevic
        description: Dir Engineering, Xvela
        image: "/images/pics/olja.jpg"
      - name: Alex Kolicich
        description: Founding Partner, 8VC
        image: "/images/pics/alex.jpg"
      - name: Philip Thomas
        description: Co-Founder, Moonlight
        image: "/images/pics/philip.jpg"
      - name: Voja Lalich
        description: Partner, StartLabs
        image: "/images/pics/voja.jpg"
      - name: Sasha Ostojic
        description: SVP Engineering, Cruise
        image: "/images/pics/sashao.jpg"
      - name: Gorjan Hrustanovic
        description: Associate, BVF
        image: "/images/pics/gorjan.png"



