theme:                      "serbianentrepreneurs.com"
title:                      "Serbian Entrepreneurs"
config:                     "config.yaml"
defaultExtension:           "md"
MetaDataFormat:             "yaml"
LanguageCode:               "en"
baseURL: "https://www.SerbianEntrepreneurs.com/"
Params:
    URL: "https://SerbianEntrepreneurs.com/"
    SocialImage: "/images/cover.jpg"
    NextMeeting:
        Month: "March"
        Day: "7"
    description: "A tight network of Serbian entrepreneurs supporting each other."
    about: "Serbian Entrepreneurs is an organization based in San Francisco."
    email: "contact@serbianentrepreneurs.com"
    Members:
      - name: Dragan Petrovic
        description: COO, Raised Series A
        image: "/images/pics/dragan.jpg"
      - name: Sasha Novakovich
        description: Investor
        image: "/images/pics/sasha.jpg"
      - name: John Milinovich
        description: CEO of URX (Exited)
        image: "/images/pics/john.jpg"
      - name: Maja Zecevic
        description: Y Combinator
        image: "/images/pics/maja.jpg"
      - name: Luka Erceg
        description: CEO + Investor
        image: "/images/pics/luka.jpg"
        