theme:                      "serbianentrepreneurs.com"
title:                      "Serbian Entrepreneurs"
config:                     "config.yaml"
defaultExtension:           "md"
MetaDataFormat:             "yaml"
LanguageCode:               "en"
baseURL: "https://www.SerbianEntrepeneurs.com/"
Params:
    URL: "https://SerbianEntrepeneurs.com/"
    SocialImage: "/images/cover.jpg"
    NextMeeting:
        Month: "March"
        Day: "7"
    description: "A tight network of Serbian entrepreneurs supporting each other."
