theme:                      "serbianentrepreneurs.com"
title:                      "Serbian Entrepreneurs"
config:                     "config.yaml"
defaultExtension:           "md"
MetaDataFormat:             "yaml"
LanguageCode:               "en"
baseURL: "https://www.SerbianEntrepreneurs.com/"
Params:
    URL: "https://SerbianEntrepreneurs.com/"
    SocialImage: "/images/cover.jpg"
    NextMeeting:
        Month: "June"
        Day: "15"
    description: "A closely-knit, invite-only network of Serbian entrepreneurs supporting each other."
    about: "Serbian Entrepreneurs is a non-profit organization based in San Francisco. Started in September 2016, the organization currently counts over 40 members primarily in the San Francisco Bay Area. Centered around an active group forum and monthly meetings, the organization provides a private venue for members to support each other."
    email: "contact@serbianentrepreneurs.com"
    Members:
      - name: Dragan Petrovic
        description: COO, Nura
        image: "/images/pics/dragan.jpg"
      - name: Brano Perkovich
        description: Chief Investment Officer, SF 49ers
        image: "/images/pics/brano.jpg"
      - name: Tihomir Bajic
        description: VP Engineering, LTSE
        image: "/images/pics/tiho.jpg"
      - name: Sasha Novakovich
        description: CEO, Alchemy
        image: "/images/pics/sasha.jpg"
      - name: Maja Zecevic
        description: CEO, Opionato
        image: "/images/pics/maja.jpg"
      - name: Lazar Stojkovic
        description: Mentor, 500 Startups
        image: "/images/pics/lazar.jpg"
      - name: John Milinovich
        description: CEO, URX (Exited)
        image: "/images/pics/john.jpg"
      - name: Luka Erceg
        description: CEO, Drylet
        image: "/images/pics/luka.jpg"
      - name: Marko Mandic
        description: CEO, Skopus Media
        image: "/images/pics/marko.jpg"
      - name: Olja Dimitrijevic
        description: Dir Engineering, Xvela
        image: "/images/pics/olja.jpg"
      - name: Alex Kolicich
        description: Founding Partner, 8VC
        image: "/images/pics/alex.jpg"
      - name: Philip Thomas
        description: CEO, Staffjoy
        image: "/images/pics/philip.jpg"
      - name: Voja Lalich
        description: Managing Partner, StartLabs Ventures
        image: "/images/pics/voja.jpg"
      - name: Sasha Ostojic
        description: SVP Engineering, Cruise Automation
        image: "/images/pics/sashao.jpg"
      - name: Gorjan Hrustanovic
        description: Associate, Biotechnology Value Fund
        image: "/images/pics/gorjan.jpg"



