theme:                      "serbianentrepreneurs-v2"
title:                      "Serbian Entrepreneurs"
config:                     "config.yaml"
defaultExtension:           "md"
MetaDataFormat:             "yaml"
LanguageCode:               "en"
baseURL: "http://www.serbianentrepreneurs.com"
Params:
    URL: "http://www.serbianentrepreneurs.com"
    SocialImage: "http://www.serbianentrepreneurs.com/images/b-bg.sq.600.png"
    NextMeetingNYC:
        Month: "December"
        Day: "13"
    NextMeetingSF:
        Month: "December"
        Day: "14"
    description: "A pay-it-forward global network of entrepreneurs fostering the Serbian startup ecosystem."
    about: "Serbian Entrepreneurs is an apolitical, non-governmental, non-profit organization started in September 2016 in Silicon Valley, by successful entrepreneurs of Serbian descent fostering the Serbian startup ecosystem around the globe through comprehensive access to skills, resources, and mentorship. We promote entrepreneurship through empowering the pay-it-forward activities of our members. Our 75 referral-based members are accomplished founders, investors, engineering leaders, and startup executives that together form a deeply vested network. Our monthly meetings provide a learning, operations, networking, and investment platform and take place in our founding city chapters: San Francisco and New York. We are next expanding to Los Angeles, California and Novi Sad, Serbia."
    email: "contact@serbianentrepreneurs.com"
    Locations:
      - name: Committee
        code: committee
      - name: San Francisco
        code: san-francisco
      - name: New York
        code: new-york
      - name: Los Angeles
        code: los-angeles
      - name: Novi Sad
        code: novi-sad
    Members:
      - name: Maja Zecevic
        description: CEO, Opionato
        image: "/images/pics/maja.jpg"
        linkedin: https://www.linkedin.com/in/zecevicmaja/
        location: committee
      - name: Iva Messy
        description: Director of HR, Altamont
        image: "/images/pics/iva.jpg"
        linkedin: https://www.linkedin.com/in/ivamessy/
        location: committee
      - name: Sasha Novakovich
        description: CEO, Alchemy
        image: "/images/pics/sasha.jpg"
        linkedin: https://www.linkedin.com/in/sashanovakovich/
        location: committee
      - name: Dragan Petrovic
        description: COO, Nura
        image: "/images/pics/dragan.jpg"
        linkedin: https://www.linkedin.com/in/dragan-petrovic-a81a74a/
        location: committee
      - name: Brano Perkovich
        description: Investor, SF 49ers
        image: "/images/pics/brano.jpg"
        linkedin: https://www.linkedin.com/in/brano-perkovich-346b9a2/
        location: committee
      - name: Philip Thomas
        description: Co-Founder, Moonlight
        image: "/images/pics/philip.jpg"
        linkedin: https://www.linkedin.com/in/philipithomas/
        location: committee
      - name: Miloš Čitaković
        description: Founder, Bridge & Fabrika.nyc
        image: "/images/pics/milos.jpg"
        linkedin: https://www.linkedin.com/in/citakovic/
        location: committee
      - name: Lazar Stojković
        description: Mentor, 500 Startups
        image: "/images/pics/lazar.jpg"
        linkedin: https://www.linkedin.com/in/lazarstojkovic/
        location: committee
      - name: Luka Erceg
        description: CEO, Drylet
        image: "/images/pics/luka.jpg"
        linkedin: https://www.linkedin.com/in/lerceg/
        location: committee
      - name: Marko Mandic
        description: CEO, Breza
        image: "/images/pics/marko.jpg"
        linkedin: https://www.linkedin.com/in/markomandic/
        location: committee
      - name: Tihomir Bajić
        description: VP Engineering, LTSE
        image: "/images/pics/tiho.jpg"
        linkedin: https://www.linkedin.com/in/tihomirbajic/
        location: committee

      - name: Lena Petrovic
        description: Attorney, Perkins
        image: "/images/pics/lena.jpg"
        linkedin: https://www.linkedin.com/in/jovanka-ciric-vujkovic-6195a71/
        location: san-francisco
      - name: Olja Dimitrijevic
        description: Dir Engineering, Xvela
        image: "/images/pics/olja.jpg"
        linkedin: https://www.linkedin.com/in/oljadimitrijevic/
        location: san-francisco
      - name: Neda Cvijetic
        description: Autonomous Vehicles, NVidia
        image: "/images/pics/neda.jpg"
        linkedin: https://www.linkedin.com/in/neda-cvijetic-4a05b17/
        location: san-francisco
      - name: Bojana Parman
        description: Engineering, RichRelevance
        image: "/images/pics/bojana.jpg"
        linkedin: https://www.linkedin.com/in/bojana-miloradovic-parman-6506892/
        location: san-francisco
      - name: Ivana Stojanovic
        description: Co-founder, Indoor Reality
        image: "/images/pics/ivana.jpg"
        linkedin: https://www.linkedin.com/in/ivana-stojanovic-6691a05/
        location: san-francisco
      - name: Jovana Knezevic
        description: Engineering, Broadway Technology
        image: "/images/pics/jovana.jpg"
        linkedin: https://www.linkedin.com/in/jovana-knezevic-a4b19420/
        location: san-francisco
      - name: Jovanka Ciric Vujkovic
        description: CEO, Knewaira
        image: "/images/pics/jovanka.jpg"
        linkedin: https://www.linkedin.com/in/jovanka-ciric-vujkovic-6195a71/
        location: san-francisco
      - name: Natasa Kordic
        description: Policy, Acumen
        image: "/images/pics/natasa.jpg"
        linkedin: https://www.linkedin.com/in/natasakordic/
        location: san-francisco
      - name: Milijana Curic
        description: EA, Andreessen Horowitz
        image: "/images/pics/milijana.jpg"
        linkedin: https://www.linkedin.com/in/milijanacuric/
        location: san-francisco

      - name: John Milinovich
        description: CEO, URX (Exited)
        image: "/images/pics/john.jpg"
        linkedin: https://www.linkedin.com/in/jmilinovich/
        location: san-francisco
      - name: Alex Kolicich
        description: Founding Partner, 8VC
        image: "/images/pics/alex.jpg"
        linkedin: https://www.linkedin.com/in/alex-kolicich-b71732a/
        location: san-francisco
      - name: Voja Lalich
        description: Partner, StartLabs
        image: "/images/pics/voja.jpg"
        linkedin: https://www.linkedin.com/in/vojalalich/
        location: san-francisco
      - name: Sasha Ostojic
        description: SVP Engineering, Cruise
        image: "/images/pics/sashao.jpg"
        linkedin: https://www.linkedin.com/in/ostojic/
        location: san-francisco
      - name: Gorjan Hrustanovic
        description: Associate, BVF
        image: "/images/pics/gorjan.png"
        linkedin: https://www.linkedin.com/in/gorjan-hrustanovic-a966a72a/
        location: san-francisco
      - name: Aleksandar Cabrilo
        description: CEO, HTEC Group
        image: "/images/pics/cabrilo.jpg"
        linkedin: https://www.linkedin.com/in/cabriloa/
        location: san-francisco
      - name: Srdjan Savicic
        description: VP, China Oceanwide
        image: "/images/pics/srdjan.jpg"
        linkedin: https://www.linkedin.com/in/savicic/
        location: san-francisco
      - name: Tony DeFranceschi
        description: Founder, iON Ventures
        image: "/images/pics/tony.jpg"
        linkedin: https://www.linkedin.com/in/tony-defranceschi-535176/
        location: san-francisco
      - name: Nebojsa Sabovic
        description: co-founder, Focure
        image: "/images/pics/nebojsa.jpg"
        linkedin: https://www.linkedin.com/in/nsabovic/
        location: san-francisco
      - name: Aleksandar Gargenta
        description: co-founder, Marakana
        image: "/images/pics/agargenta.jpg"
        linkedin: https://www.linkedin.com/in/aleksandargargenta/
        location: san-francisco
      - name: Armann Kojich
        description: Founder, Greenvolt & Apon
        image: "/images/pics/armann.jpg"
        linkedin: https://www.linkedin.com/in/armann/
        location: san-francisco
      - name: Ivan Smiljanic
        description: Partner, IPGSF
        image: "/images/pics/ivans.jpg"
        linkedin: https://www.linkedin.com/in/ivansmiljanic/
        location: san-francisco
      - name: Marko Ugrenovic
        description: Co-founder, Techsource
        image: "/images/pics/markou.jpg"
        linkedin: https://www.linkedin.com/in/markougrenovic/
        location: san-francisco
      - name: Perry Narancic
        description: Principal, LexAnalytica
        image: "/images/pics/perry.jpg"
        linkedin: https://www.linkedin.com/in/perrynarancic/
        location: san-francisco
      - name: Stefan Savicic
        description: Co-founder, Nooflux
        image: "/images/pics/stefansavicic.jpg"
        linkedin: https://www.linkedin.com/in/stefan-savicic/
        location: san-francisco
      - name: Milan Mitrovic
        description: Co-founder, Smoke & Mirrors
        image: "/images/pics/milan.jpg"
        linkedin: https://www.linkedin.com/in/milan-mitrovic-yu/
        location: san-francisco
      - name: Zoran Zoran
        description: Purchasing, Solaria
        image: "/images/pics/zoran.jpg"
        linkedin: https://www.linkedin.com/in/zoran-zoran-a15398134/
        location: san-francisco
      - name: Nikola Otasevic
        description: CEO, Refdash
        image: "/images/pics/nikolao.jpg"
        linkedin: https://www.linkedin.com/in/nikola-otasevic-4136571a/
        location: san-francisco
      - name: Milos Ribic
        description: Director, Adidas Corporate Venture
        image: "/images/pics/milosr.jpg"
        linkedin: https://www.linkedin.com/in/milos-ribic-4164a113/
        location: san-francisco
      - name: Nikola Bozinovic
        description: CEO, Frame
        image: "/images/pics/nikola.jpg"
        linkedin: https://www.linkedin.com/in/nikolabozinovic/
        location: san-francisco
      - name: Ranko Sredojevic
        description: CEO, Numericcal
        image: "/images/pics/ranko.jpg"
        linkedin: https://www.linkedin.com/in/ranko-r-sredojevic-4b8ba61a/
        location: san-francisco
      - name: Stefan Stokic
        description: CEO, Slik
        image: "/images/pics/stefanstokic.jpg"
        linkedin: https://www.linkedin.com/in/stefanstokic/
        location: san-francisco
      - name: Nikola Curic
        description: Corporate FP&A, Shutterfly
        image: "/images/pics/nikolac.jpg"
        linkedin: https://www.linkedin.com/in/nikolacuric/
        location: san-francisco
      - name: Aca Gacic
        description: Co-founder & CTO, EmbraceFamily Health
        image: "/images/pics/acag.jpg"
        linkedin: https://www.linkedin.com/in/aca-gacic-63a4816/
        location: san-francisco
      - name: Nemanja Cerovac
        description: Co-founder, LaptopFriendly
        image: "/images/pics/nemanjac.jpg"
        linkedin: https://www.linkedin.com/in/ncerovac/
        location: san-francisco

      - name: Filip Bajovic
        description: CEO, Label Kings
        image: "/images/pics/filip.jpg"
        linkedin: https://www.linkedin.com/in/filip-bajovic-6a074939/
        location: new-york
      - name: Sasha Jokic
        description: CEO, Formdwell
        image: "/images/pics/sashaj.jpg"
        linkedin: https://www.linkedin.com/in/sasha-jokic-68b09127/
        location: new-york
      - name: Vladimir Vukicevic
        description: CEO, Meural
        image: "/images/pics/vlad.jpg"
        linkedin: https://www.linkedin.com/in/vukicevic/
        location: new-york
      - name: Nemanja Petrovic
        description: Technical Lead, Google
        image: "/images/pics/nemanja.png"
        linkedin: http://www.ifp.illinois.edu/~nemanja/resume.html
        location: new-york
      - name: Bojan Bajic
        description: Associate, Ares Management
        image: "/images/pics/bojan.jpg"
        linkedin: https://www.linkedin.com/in/bojanbajic/
        location: new-york
      - name: Aleksandar Jovicic
        description: CEO, Sembient
        image: "/images/pics/aleksj.jpg"
        linkedin: https://www.linkedin.com/in/aleksandar-jovicic-a206bba/
        location: new-york
      - name: Petar Mirovic
        description: CEO, EnGoPlanet
        image: "/images/pics/petarm.jpg"
        linkedin: https://www.linkedin.com/in/petar-mirovic/
        location: new-york

      - name: Nina Montée Karp
        description: Co-founder, Happiest Baby
        image: "/images/pics/nina.jpg"
        linkedin: https://www.linkedin.com/in/nina-mont%C3%A9e-karp-234a8885/
        location: los-angeles
      - name: Andrej Kostresevic
        description: CEO, Nomads & Expack
        image: "/images/pics/andrej.jpg"
        linkedin: https://www.linkedin.com/in/andrejkostresevic/
        location: los-angeles
      - name: Slaven Moro
        description: CEO, Entropia Health
        image: "/images/pics/slaven.jpg"
        linkedin: https://www.linkedin.com/in/slaven-moro-phd-10b4637/
        location: los-angeles

      - name: Marko Gacesa
        description: Founder & CPO, Alchemy
        image: "/images/pics/markog.jpg"
        linkedin: https://www.linkedin.com/in/slaven-moro-phd-10b4637/
        location: novi-sad
      - name: Mirko Topalski
        description: CEO, Eipix Entertainment
        image: "/images/pics/mirko.jpg"
        linkedin: https://www.linkedin.com/in/mirkotopalski/
        location: novi-sad
      - name: Martin Pavlik
        description: CEO, Pet2Net
        image: "/images/pics/martin.jpg"
        linkedin: https://www.linkedin.com/in/martin-pavlik-85046827/
        location: novi-sad
      - name: Nenad Milanovic
        description: CEO, Coing
        image: "/images/pics/nenad.jpg"
        linkedin: https://www.linkedin.com/in/milanovicnenad/
        location: novi-sad



