theme:                      "serbianentrepreneurs.com"
title:                      "Serbian Entrepreneurs"
config:                     "config.yaml"
defaultExtension:           "md"
MetaDataFormat:             "yaml"
LanguageCode:               "en"
baseURL: "https://www.SerbianEntrepreneurs.com/"
Params:
    URL: "https://SerbianEntrepreneurs.com/"
    SocialImage: "/images/cover.jpg"
    NextMeeting:
        Month: "June"
        Day: "15"
    description: "A closely-knit, invite-only network of Serbian entrepreneurs supporting each other."
    about: "Serbian Entrepreneurs is a non-profit, pay-it-forward organization based in San Francisco. Started in September 2016 as an invite-only group, the organization has grown to over 40 active members. Centered around a group forum and monthly meetings, Serbian Entrepreneurs is a private venue and support network for our member entrepreneurs."
    email: "contact@serbianentrepreneurs.com"
    Members:
      - name: Dragan Petrovic
        description: COO, Nura
        image: "/images/pics/dragan.jpg"
      - name: Brano Perkovich
        description: Investor, SF 49ers
        image: "/images/pics/brano.jpg"
      - name: Tihomir Bajic
        description: VP Engineering, LTSE
        image: "/images/pics/tiho.jpg"
      - name: Sasha Novakovich
        description: CEO, Alchemy
        image: "/images/pics/sasha.jpg"
      - name: Maja Zecevic
        description: CEO, Opionato
        image: "/images/pics/maja.jpg"
      - name: Lazar Stojkovic
        description: Mentor, 500 Startups
        image: "/images/pics/lazar.jpg"
      - name: John Milinovich
        description: CEO, URX (Exited)
        image: "/images/pics/john.jpg"
      - name: Luka Erceg
        description: CEO, Drylet
        image: "/images/pics/luka.jpg"
      - name: Marko Mandic
        description: CEO, Skopus Media
        image: "/images/pics/marko.jpg"
      - name: Olja Dimitrijevic
        description: Dir Engineering, Xvela
        image: "/images/pics/olja.jpg"
      - name: Alex Kolicich
        description: Founding Partner, 8VC
        image: "/images/pics/alex.jpg"
      - name: Philip Thomas
        description: Co-Founder, Moonlight
        image: "/images/pics/philip.jpg"
      - name: Voja Lalich
        description: Partner, StartLabs
        image: "/images/pics/voja.jpg"
      - name: Sasha Ostojic
        description: SVP Engineering, Cruise
        image: "/images/pics/sashao.jpg"
      - name: Gorjan Hrustanovic
        description: Associate, BVF
        image: "/images/pics/gorjan.png"



